CREATE VIEW [etljob].[vw_RecoveryItem]
AS
SELECT [RecoveryItemId]
      ,[JobStepClusterID]
      ,[ClientID]
      ,[JobExecutionID]
      ,[StopID]
	  ,[Scheduled]
      ,[RecoveryType]
      ,[RecoveryPriority]
	  ,[RecoveryStart]
      ,[RecoveryEnd]
	  ,[SSISExecutionID]
	  ,[RecoveringJobExecutionID]
	  ,[InitRecoveryId] 
	  ,[ExecRecoveryId]
	  ,[ETLStatusID]
	  ,[ETLStatusSource]
      ,[Message]
FROM [etljob].[RecoveryItem]